export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_ERROR = "GET_INGREDIENTS_ERROR";

export const CONSTRUCTOR_ADD = "CONSTRUCTOR_ADD";
export const CONSTRUCTOR_DELETE = "CONSTRUCTOR_DELETE";
export const CONSTRUCTOR_UPDATE = "CONSTRUCTOR_UPDATE";
export const CONSTRUCTOR_RESET = "CONSTRUCTOR_RESET";

export const INGREDIENT_MODAL_SET = "INGREDIENT_MODAL_SET";
export const INGREDIENT_MODAL_DELETE = "INGREDIENT_MODAL_DELETE";

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILED = "CREATE_ORDER_FAILED";
