
export const GET_INGREDIENTS:"GET_INGREDIENTS" = "GET_INGREDIENTS";
export const GET_INGREDIENTS_SUCCESS:"GET_INGREDIENTS_SUCCESS" = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_ERROR:"GET_INGREDIENTS_ERROR" = "GET_INGREDIENTS_ERROR";

export const CONSTRUCTOR_ADD:"CONSTRUCTOR_ADD" = "CONSTRUCTOR_ADD";
export const CONSTRUCTOR_DELETE:"CONSTRUCTOR_DELETE" = "CONSTRUCTOR_DELETE";
export const CONSTRUCTOR_UPDATE:"CONSTRUCTOR_UPDATE" = "CONSTRUCTOR_UPDATE";
export const CONSTRUCTOR_RESET:"CONSTRUCTOR_RESET" = "CONSTRUCTOR_RESET";

export const CREATE_ORDER_REQUEST:"CREATE_ORDER_REQUEST" = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS:"CREATE_ORDER_SUCCESS" = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILED:"CREATE_ORDER_FAILED" = "CREATE_ORDER_FAILED";

export const REGISTRATION_REQUEST:"REGISTRATION_REQUEST" = "REGISTRATION_REQUEST";
export const REGISTRATION_SUCCESS:"REGISTRATION_SUCCES" = "REGISTRATION_SUCCES";
export const REGISTRATION_FAILED:"REGISTRATION_FAILED" = "REGISTRATION_FAILED";


export const LOGIN_REQUEST:"LOGIN_REQUEST"= "LOGIN_REQUEST";
export const LOGIN_SUCCESS:"LOGIN_SUCCES" = "LOGIN_SUCCES";
export const LOGIN_FAILED:"LOGIN_FAILED" = "LOGIN_FAILED";

export const LOGOUT_REQUEST:"LOGOUT_REQUEST" = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS:"LOGOUT_SUCCESS" = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED:"LOGOUT_FAILED" = "LOGOUT_FAILED";

export const FORGOT_PASSWORD_REQUEST:"FORGOT_PASSWORD_REQUEST" = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS:"FORGOT_PASSWORD_SUCCESS" = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILED:"FORGOT_PASSWORD_FAILED" = "FORGOT_PASSWORD_FAILED";

export const RESET_PASSWORD_REQUEST:"RESET_PASSWORD_REQUEST" = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS:"RESET_PASSWORD_SUCCESS" = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED:"RESET_PASSWORD_FAILED" = "RESET_PASSWORD_FAILED";

export const GET_USER_DATA_REQUEST:"GET_USER_DATA_REQUEST" = "GET_USER_DATA_REQUEST"; 
export const GET_USER_DATA_SUCCESS:"GET_USER_DATA_SUCCESS" = "GET_USER_DATA_SUCCESS"; 
export const GET_USER_DATA_FAILED:"GET_USER_DATA_FAILED" = "GET_USER_DATA_FAILED"; 

export const SET_USER_DATA_REQUEST:"SET_USER_DATA_REQUEST" = "SET_USER_DATA_REQUEST"; 
export const SET_USER_DATA_SUCCESS:"SET_USER_DATA_SUCCESS" = "SET_USER_DATA_SUCCESS"; 
export const SET_USER_DATA_FAILED:"SET_USER_DATA_FAILED" = "SET_USER_DATA_FAILED"; 

export const WS_CONNECTION_START:'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS:'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR:'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED:'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_GET_MESSAGE:'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
export const WS_SEND_MESSAGE:'WS_SEND_MESSAGE' = 'WS_SEND_MESSAGE';