import {WS_CONNECTION_START,
  WS_CONNECTION_SUCCESS,
  WS_CONNECTION_ERROR,
  WS_CONNECTION_CLOSED, 
  WS_GET_MESSAGE,
  WS_SEND_MESSAGE} from '../types'




export const wsActions = {
  onStart: WS_CONNECTION_START,
  onClose: WS_CONNECTION_CLOSED,
  onSend: WS_SEND_MESSAGE,
  onOpen: WS_CONNECTION_SUCCESS,
  onClose: WS_CONNECTION_CLOSED,
  onError: WS_CONNECTION_ERROR,
  onMessage: WS_GET_MESSAGE
}